---
version: 2

project_name: wardend

before:
  hooks:
    # setup musl
    - apk add gcc musl-dev linux-headers
    # setup libwasmvm
    - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a
    # you may remove this if you don't need go generate
    - go generate ./...
env:
  - CGO_ENABLED=1
builds:
  - id: wardend-linux-amd64
    main: ./cmd/wardend
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=warden
      - -X github.com/cosmos/cosmos-sdk/version.AppName=wardend
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -linkmode=external
      - -extldflags '-static'
    tags:
      - netgo
      - muslc

archives:
  - id: w/version
    builds:
      - wardend-linux-amd64
    name_template: '{{ .ProjectName }}d_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    format: zip
    files:
      - none*
  - id: wo/version
    builds:
      - wardend-linux-amd64
    name_template: '{{ .ProjectName }}d_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    format: zip
    files:
      - none*
  - id: binary
    builds:
      - wardend-linux-amd64
    name_template: '{{ .ProjectName }}d_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    format: binary
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}d_v{{ .Version }}_checksums.txt'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-releaser
    image_templates:
      - 'ghcr.io/warden-protocol/{{ .ProjectName }}d-dev:{{if eq .Env.RELEASE "true"}}v{{ .Version }}{{else}}{{ .ShortCommit }}{{end}}-amd64'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}d"
      - "--label=org.opencontainers.image.description={{.ProjectName}}d"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.url=https://wardenprotocol.org"
      - "--label=org.opencontainers.image.source=https://github.com/warden-protocol/wardenprotocol"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
