---
name: Release Wardend development image

on:
  push:
    branches:
      - main
    paths:
      - "cmd/wardend/**"
      - "warden/**"
      - "precompiles/**"
    tags:
      - "wardend/v*"
  pull_request:
    paths:
      - "cmd/wardend/**"
      - "warden/**"
      - "precompiles/**"

jobs:
  release-dev:
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - lint
      - unit-test
    permissions:
      actions: read
      contents: write
      packages: write
    uses: ./.github/workflows/release-dev.yml
    with:
      app_name: wardend
    secrets: inherit
